
version: '2'
services:

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
          default:                  # DO NOT DELETE
          net_redis:
            ipv4_address: 172.21.0.10 #static IP - this should not be scaled

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
        default:                  # DO NOT DELETE
        net_mongo:
          ipv4_address: 172.22.0.10 #static IP - this should not be scaled

#https://www.cloudamqp.com/blog/2017-12-29-part1-rabbitmq-best-practice.html
#http://www.squaremobius.net/amqp.node/channel_api.html#channel_bindQueue
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
#      DEFAULT_PERMISSIONS: [".*", ".*", ".*"]
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./DockerData/postgres:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

 
networks:
  net_redis:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

  net_mongo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
