
version: '3.6'
services:

  bks_redis:
    image: "redis:alpine"
    container_name: bks_redis
    volumes:
      - ./DockerData/redis/data:/var/lib/redis
      - ./DockerData/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - bks

#https://www.shellhacks.com/ru/mongodb-create-user-database-admin-root/
#https://zgadzaj.com/development/docker/docker-compose/containers/mongodb
#https://medium.com/@MaxouMask/secured-mongodb-container-6b602ef67885
  bks_mongo:
    image: mongo:latest
    container_name: bks_mongo
    environment:
#      MONGO_INITDB_DATABASE: gps
#      MONGO_INITDB_USERNAME: user
#      MONGO_INITDB_PASSWORD: user
#      MONGO_INITDB_DATABASE: gps
       MONGO_INITDB_ROOT_USERNAME: root_username
       MONGO_INITDB_ROOT_PASSWORD: very_secure_root_pass

    volumes:
      - ./bind_mounts/mongo/entrypoint:/docker-entrypoint-initdb.d #!!! executed just when db is created
   #   - ./bind_mounts/mongo:/app/data
      - ./DockerData/mongo1:/data/db
    ports:
      - "27017:27017"
    networks:
      - bks

#https://www.cloudamqp.com/blog/2017-12-29-part1-rabbitmq-best-practice.html
#http://www.squaremobius.net/amqp.node/channel_api.html#channel_bindQueue
  bks_rabbit:
    image: "rabbitmq:3-management"
    container_name: bks_rabbit
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
#      DEFAULT_PERMISSIONS: [".*", ".*", ".*"]
    volumes:
#      - ./DockerData/postgres/etc/:/etc/rabbitmq/
      - ./DockerData/postgres/data/:/var/lib/rabbitmq/
      - ./DockerData/postgres/logs/:/var/log/rabbitmq/
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq_1"
    networks:
      - bks

  bks_postgres:
    image: postgres:latest
    container_name: bks_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./DockerData/postgres:/var/lib/postgresql/data
    networks:
      - bks

  bks_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bks_pgadmin
    depends_on:
      - bks_postgres
    ports:
      - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - bks

  bks_nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx
    container_name: bks_nginx
    network_mode: "host"    #Enable forwarding from Docker containers to the outside world
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=nest
      - LOCAL_HOST=127.0.0.1
      - NEST_PORT=3001
      - NGINX_MAX_BODY=100M
    volumes:
      - ./static/coastalvit:/app/public
    ports:
      - 80:80
#    networks:
#      - bks


volumes:
  # default dir on Ubuntu /var/lib/docker/volumes
  data_containerX: 

networks:
  bks:



